# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

before_install:
  - pip install --progress-bar off --user numpy tensorflow
  
after_success:
    - Rscript -e 'covr::codecov()'
