# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

before_install:
  - pip install --progress-bar off --user numpy tensorflow
  - sudo apt-get -y install gdal-bin

addons:
  apt:
    packages:
      - libudunits2-dev
      - gdal-bin
      - libproj-dev
      - proj-data
      - proj-bin
      - libgeos-dev

after_success:
    - Rscript -e 'covr::codecov()'
