# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r_packages: covr

env:
   global:
     - CODECOV_TOKEN='4dea778a-b555-43b5-a8c0-971e75a4c26b'

before_install:
  - pip install --progress-bar off --user numpy tensorflow
  - sudo apt-get install gdal-bin proj-bin libgdal-dev libproj-dev

after_success:
- Rscript -e 'library(covr); codecov()'

addons:
  apt:
    packages:
      - libudunits2-dev
      - gdal-bin
      - libproj-dev
      - proj-data
      - proj-bin
      - libgeos-dev
