#' Predict IUCN Categories from Features
#'
#' Uses a model generated with \code{\link{train_iucnn}} to predict the IUCN status of
#' Not Evaluated or Data Deficient species based on features, for instance generated
#' from species occurrence records with \code{\link{geo_features}}, \code{\link{clim_features}}, and \code{\link{biome_features}}.
#' The same features in the same order must be used for training and fitting.
#'
#'
#'@param x a data.set, containing a column "species" with the species names, and
#'subsequent columns with different features, in the same order as used for \code{\link{train_iucnn}}.
#'@param model.dir a character string. The folder with the trained IUCNN model as generated by \code{\link{train_iucnn}}.
#'@param return_prob logical. Should the probabilities for the labels be returned? Default is FALSE.
#'
#'@note See \code{vignette("Approximate_IUCN_Red_List_assessments_with_IUCNN")} for a
#'tutorial on how to run IUCNN.
#'
#'@return a vector with the predicted labels for the input species.
#'
#' @examples
#'\dontrun{
#'dat <- data.frame(species = c("A", "B")
#'                 decimallongitude = runif (200,-5,5),
#'                 decimallatitude = runif (200,-5,5))
#'labels <- c(1,0)
#'
#'train_feat <- geo_features(dat)
#'
#'not_eval <- data.frame(species = c(A", "B")
#'                 decimallongitude = runif (200,-5,5),
#'                 decimallatitude = runif (200,-5,5))
#'
#'predict_feat <- geo_features(not_eval)
#'
#'train_iucnn(x = train_feat,
#'            label = labels)
#'
#'
#'predict_iucnn(x = predict_feat,
#'              model_dir = iuc_nn_model")
#'}
#'
#'
#' @export
#' @importFrom reticulate source_python
#' @importFrom magrittr %>%
#' @importFrom dplyr select
#' @importFrom stats complete.cases

predict_iucnn <- function(x,
                          model_dir,
                          return_prob = FALSE){

  # complete cases only
  tmp.in <- x[complete.cases(x),]

  if(nrow(tmp.in) != nrow(x)){
    mis <- x[!complete.cases(x),]
    warning("Information for species was incomplete, species removed\n", paste(mis$species, "\n"))
  }

  #prepare input data
  tmp <- tmp.in %>%
    dplyr::select(-.data$species)

  # source python function
  reticulate::source_python('inst/python/IUCNN_predict.py')

  # run predict function
  out <- iucnn_predict(feature_set = as.matrix(tmp),
                       model_dir = model_dir,
                       verbose = 0,
                       return_prob = return_prob)

  #return output object
  out <- bind_cols(tmp %>% select(.data$species),
                   out)

  return(out)
}


